In [1]:
import numpy as np

In [2]:
list =[[1,2,3],[4.5,5.6,6.],['a','b','c']]
x = np.array(list)
x

array([['1', '2', '3'],
       ['4.5', '5.6', '6.0'],
       ['a', 'b', 'c']], dtype='<U32')

In [3]:
x = np.full(shape=(3,4,2), fill_value = 10)
x

array([[[10, 10],
        [10, 10],
        [10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10],
        [10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10],
        [10, 10],
        [10, 10]]])

In [4]:
x = np.zeros(shape=(3,2,2), dtype = 'int32')
x

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

In [5]:
x = np.arange(1,51,1)
y = x.reshape(5,5,2)
y

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36],
        [37, 38],
        [39, 40]],

       [[41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50]]])

In [6]:
y[3:,2:3,0:1]

array([[[35]],

       [[45]]])

In [7]:
x = np.array([[[1,7],[2,8],[3,9]], [[4,11],[5,10],[6,12]]])
x

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 11],
        [ 5, 10],
        [ 6, 12]]])

In [8]:
x[:2,1:2]

array([[[ 2,  8]],

       [[ 5, 10]]])

In [9]:
int_array = np.arange(5)
print('Intial Datatye is:',int_array.dtype)
float_array = int_array.astype('complex128')
print('Changed Datatye is:',float_array.dtype)
float_array

Intial Datatye is: int64
Changed Datatye is: complex128


array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [10]:
y.ndim

3

In [11]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [13]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
x=np.zeros(shape=(5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
x=np.linspace(0,15,5)
x

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [16]:
x=np.arange(0,10,2)
x


array([0, 2, 4, 6, 8])

In [17]:
a = np.arange(10)

In [18]:
b = a

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a[2] = 10
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [22]:
b

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [23]:
int_array = np.arange(5)
int_array1 = int_array.astype('int32')



In [24]:
int_array

array([0, 1, 2, 3, 4])

In [25]:
int_array1

array([0, 1, 2, 3, 4], dtype=int32)

In [26]:
int_array[1] = 10

In [27]:
int_array

array([ 0, 10,  2,  3,  4])

In [28]:
int_array1

array([0, 1, 2, 3, 4], dtype=int32)

In [29]:
x = np.arange(1,51,1)
y = x.reshape(5,5,2)
y[0][0][0] = 5
y

array([[[ 5,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36],
        [37, 38],
        [39, 40]],

       [[41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50]]])

In [30]:
np.sort(y,axis=0)

array([[[ 5,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36],
        [37, 38],
        [39, 40]],

       [[41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50]]])

In [31]:
x  = np.arange(10).reshape(2,5)
y = np.arange(10).reshape(2,5)

In [32]:
x[0][0]=11
x[1][0]=10
x

array([[11,  1,  2,  3,  4],
       [10,  6,  7,  8,  9]])

In [33]:
np.sort(x)

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [34]:
np.sort(x,axis=0)

array([[10,  1,  2,  3,  4],
       [11,  6,  7,  8,  9]])

In [35]:
np.sort(x,axis=1)

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [36]:
x.sort()

In [37]:
x

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [38]:
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  4, 11,  0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10,  5,  6,  7,  8,  9]])

In [39]:
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [40]:
np.hstack((x,y))

array([[ 1,  2,  3,  4, 11,  0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10,  5,  6,  7,  8,  9]])

In [41]:
np.vstack((x,y))

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [42]:
x

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [43]:
x.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [11, 10]])

In [44]:
x.flatten()

array([ 1,  2,  3,  4, 11,  6,  7,  8,  9, 10])

In [45]:
x

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [46]:
np.hstack((x[0],x[1]))

array([ 1,  2,  3,  4, 11,  6,  7,  8,  9, 10])

In [47]:
x

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [48]:
np.flip(x) ## Both Rows and Columns

array([[10,  9,  8,  7,  6],
       [11,  4,  3,  2,  1]])

In [49]:
np.flip(x,axis=0) ## Only Rows

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4, 11]])

In [50]:
np.flip(x,axis=1) ## Only Columns

array([[11,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [51]:
x

array([[ 1,  2,  3,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [52]:
y = np.ravel(x) ## faltten vs Ravel
y

array([ 1,  2,  3,  4, 11,  6,  7,  8,  9, 10])

In [53]:
y[2] = 33
y


array([ 1,  2, 33,  4, 11,  6,  7,  8,  9, 10])

In [54]:
x

array([[ 1,  2, 33,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [55]:
?np.random.uniform

In [56]:
x

array([[ 1,  2, 33,  4, 11],
       [ 6,  7,  8,  9, 10]])

In [57]:
x = [[1,2],[5,6]]
y = [[2,5],[7,8]]
x = np.array(x)
y = np.array(y)

In [58]:
x

array([[1, 2],
       [5, 6]])

In [59]:
y

array([[2, 5],
       [7, 8]])

In [60]:
np.dot(x,y)

array([[16, 21],
       [52, 73]])

In [61]:
x * y

array([[ 2, 10],
       [35, 48]])

In [62]:
np.matmul(x,y)

array([[16, 21],
       [52, 73]])

In [63]:
x @ y

array([[16, 21],
       [52, 73]])