# Numpy DIY 

In [1]:
import numpy as np 
print(np.__version__)

1.21.5


### Qn 1. Create a 1D array of numbers from 0 to 11
Desired output: 
  `array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

In [2]:
# Type your code below
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Qn 1.2 Print the data type of the array

In [3]:
# Type your code below
x.dtype

dtype('int64')

#### Qn1.3 Change the dtype to `float64`

In [4]:
# Type your code below
y=x.astype('float64')
y.dtype

dtype('float64')

### Qn 2. Extract all odd numbers from arr

Input: `arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`

Desired output: 
  `array([1, 3, 5, 7, 9])`

In [5]:
# Type your code below
odd = np.where(x%2!=0)
odd

(array([1, 3, 5, 7, 9]),)

### Q3. Convert a 1D array to a 2D array with 2 rows

Input: np.arange(10)

Desired Output:

  ```
  array([[0, 1, 2, 3, 4],
          [5, 6, 7, 8, 9]])
  ```

In [6]:
# Type your code below
reshape = np.arange(10).reshape(2,5)
reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])


### Q4. Stack arrays a and b vertically

Input

  ```
  a = np.arange(10).reshape(2,-1)
  b = np.repeat(1, 10).reshape(2,-1)
  ```

Desired Output:

  ```
  > array([[0, 1, 2, 3, 4],
  >        [5, 6, 7, 8, 9],
  >        [1, 1, 1, 1, 1],
  >        [1, 1, 1, 1, 1]])
  ```


In [7]:
# Type your code below
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
vstack = np.concatenate((a,b))
print(vstack)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Q5. Get the positions where elements of a and b match

Input:

  ```
  a = [1,2,3,2,3,4,3,4,5,6]
  b = [7,2,10,2,7,4,9,4,9,8]
  ```

Desired Output:

  ```
  > (array([1, 3, 5, 7]),)
  ```

In [8]:
a = [1,2,3,2,3,4,3,4,5,6]
b = [7,2,10,2,7,4,9,4,9,8]

common =[] 
for i in range(len(a)):
    if (a[i]==b[i]):
        common.append(i)
        
common_array = np.array(common)
common_array

array([1, 3, 5, 7])

### Q6: Swap columns 1 and 2 in the array arr.

Input: 

  ```
  arr = np.arange(9).reshape(3,3)
  ```



In [9]:
# Type your code below
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[1,2]] = arr [:,[2,1]]
print('Swapped Columns==')
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Swapped Columns==
[[0 2 1]
 [3 5 4]
 [6 8 7]]


### Q7: Swap rows 1 and 2 in the array arr:

Input:
  ```
  arr = np.arange(9).reshape(3,3)
  ```

In [10]:
# Type your code below
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,2],:] = arr [[2,1],:]
print('Swapped Rows==')
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Swapped Rows==
[[0 1 2]
 [6 7 8]
 [3 4 5]]


### Q8. Reverse the rows of a 2D array arr.

Input:

```
arr = np.arange(9).reshape(3,3)
```

In [11]:
# Type your code below
arr = np.arange(9).reshape(3,3)
print(arr)
print('===Reversed Rows===')
print(np.flip(arr,axis=1)) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
===Reversed Rows===
[[2 1 0]
 [5 4 3]
 [8 7 6]]


### Q9. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [12]:
# Type your code below
arr = np.random.uniform(5,10,(5,3))
arr

array([[8.02442023, 5.27121777, 7.67146049],
       [7.4184814 , 9.90414442, 6.21259268],
       [8.412925  , 7.83253858, 5.20870639],
       [9.36033868, 5.08314138, 5.56185428],
       [5.74885019, 7.36613189, 9.16581456]])

### Q10: Consider the below array

`array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

#### Q10.1 Create a slice of the array containing the following values:  `array([5, 6, 7])`

In [13]:
# Type your code below
arr = np.arange(10)
arr[5:8]

array([5, 6, 7])

#### Q10.2 Modify the given array to the below format 
``` array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9]) ```

In [14]:
# Type your code below
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])


### Q11: Drop all nan values from a 1D numpy array

Input:

  ```
    a = [1,2,3,np.nan,5,6,7,np.nan]
  ```

Desired Output:

  ```
  array([ 1.,  2.,  3.,  5.,  6.,  7.])
  ```


In [15]:
# Type your code below
a = [1,2,3,np.nan,5,6,7,np.nan]
a.remove(np.nan)
a.remove(np.nan)
arr = np.array(a,dtype='float64')
arr

array([1., 2., 3., 5., 6., 7.])

### Q12: Create an empty, ones and zero array with 6, 3, and 4 elements respectively

In [16]:
# Type your code below
empty = np.empty([6,])
print(empty)
zeros = np.zeros([3,])
print(zeros)
one = np.ones([4,])
print(one)

[1. 2. 3. 5. 6. 7.]
[0. 0. 0.]
[1. 1. 1. 1.]


### Q13: Create a 4x4 array with all elements value set to 23.67

In [17]:
# Type your code below
x = np.full(shape=(4,4), fill_value = 23.67)
x

array([[23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67]])

### Qn14: Create an array with eight values that are spaced linearly in the [13, 27] interval

In [18]:
# Type your code below
x = np.linspace(13,27,8)
x

array([13., 15., 17., 19., 21., 23., 25., 27.])

# Optional Questions


## Qn15: Use NumPy to create a random array with 50 random numbers, maximum number should be less than 1000 

In [19]:
# Type your code below
arr = np.random.uniform(high=1000,size=50)
arr

array([822.91324356, 642.44842695, 830.20079792, 122.61504741,
       921.31112263, 168.00945815,  61.94200548,  94.93301927,
       460.44492894, 515.51682563, 627.96906684, 871.50084471,
       747.57839724, 502.91162569, 279.67503475,  37.08474625,
       393.47133665, 366.57149603, 776.2771801 , 236.19698272,
        32.02048338, 979.31869887, 982.75139512, 415.37212894,
       470.13054215, 585.01157001, 780.86750296, 976.95726014,
        73.51343589,  54.55637086, 369.47483995, 282.74305432,
       550.39043889, 594.13986812,  22.96485082, 243.50512677,
       627.62776004, 677.10798009, 504.84288382, 465.22975973,
       815.70231032, 622.12221517, 928.8115596 , 284.03619371,
        76.90577389, 195.08945079, 216.19777993, 987.82054072,
       498.06756667, 694.80964841])

## Qn16: Improve answer in Qn15 to always return same random numbers


In [20]:
# Type your code below
np.random.seed(1000)
arr = np.random.uniform(high=1000,size=50)
arr

array([653.58958546, 115.00694312, 950.28286435, 482.19140143,
       872.47453518, 212.33268092,  40.70962477, 397.19446135,
       233.13219735, 841.74072425, 207.08234439, 742.46953358,
       392.15412781, 182.25651995, 743.53941459,  69.58208097,
       885.33720438, 952.64439922, 931.14343468, 415.43095304,
        28.98165939, 982.0274846 , 339.63768364, 706.68719389,
       361.87706761,  35.10589795, 855.05825324, 657.25350814,
       765.68299415, 554.087238  , 885.09293661, 904.1976154 ,
        10.42170056,  74.55673614, 244.62920976, 133.30475245,
       697.92510041, 398.20488353, 883.1221914 , 181.00751027,
       432.49917179,  18.14320275, 691.43786169, 469.69065204,
       128.22218965, 891.33705129, 918.20362447,  73.12099368,
        45.44794323, 438.57289574])

## Qn17: Find a way to generate randon words

In [21]:
# Type your code below
